# An example of a services.yaml file in an extension

services:

  _defaults:
    autowire: true
    autoconfigure: true

  Jeschek\DragSort\Controller\Controller:
    tags: [ 'controller.service_arguments' ]