nelmio_api_doc:
    documentation:
        info:
            title: Yoshi Kan API Reference
            description: Yoshi Kan ledenbeheer en website 
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/mm/api(?!/doc$) # Accepts routes under /api except /api/doc
