version: '3.1'

services:
  
  # --------------------------------------------------------------------------------------------------------------------
  # MySQL database server
  # --------------------------------------------------------------------------------------------------------------------
  
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USER=yoshikan
      - MYSQL_PASSWORD=yoshikan
      - MYSQL_DATABASE=yoshikan
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_ONETIME_PASSWORD=0
    # left out ONLY_FULL_GROUP_BY below to enable hacky group-by functionality in SimpleReadModelDBALRepository
    # this is no problem since we have this on the real server as well.
    command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION --max_allowed_packet=32505856000 --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
  
  # --------------------------------------------------------------------------------------------------------------------
  # Nginx webserver
  # --------------------------------------------------------------------------------------------------------------------
  
  httpd:
    image: nginx:alpine
    working_dir: /opt/app
    volumes:
      - .:/opt/app
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "8080:8080"
    depends_on:
      - php
    
  # --------------------------------------------------------------------------------------------------------------------
  # PHP 8.2 container
  # --------------------------------------------------------------------------------------------------------------------
  
  php:
    image: wodby/php:8.2
    working_dir: /opt/app
    depends_on:
      - mysql
    environment:
      - PHP_IDE_CONFIG=serverName=locodio-with-compose
      - PHP_DATE_TIMEZONE=Europe/Brussels
      - COMPOSER_ALLOW_SUPERUSER=1
      # - DATABASE_URL="mysql://yoshikan:yoshikan@mysql:3306/yoshikan"
      - PHP_FPM_USER=wodby
      - PHP_FPM_GROUP=wodby
    volumes:
      - .:/opt/app
      - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini    
  
  # --------------------------------------------------------------------------------------------------------------------
  # Mailhog - https://github.com/mailhog/MailHog
  # --------------------------------------------------------------------------------------------------------------------
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  # --------------------------------------------------------------------------------------------------------------------
  # Documentation  
  # --------------------------------------------------------------------------------------------------------------------
  
  docs:
    image: nginx:alpine
    volumes:
      - ./docs/docs/.vuepress/dist:/usr/share/nginx/html      
    ports:
      - "8081:80"

  # --------------------------------------------------------------------------------------------------------------------
  # Composer and Node installers & frontend builders 
  # --------------------------------------------------------------------------------------------------------------------

#  php-vendor-builder:
#    image: wodby/php:8.2
#    working_dir: /opt/app
#    volumes:
#      - .:/opt/app
#    command: bash -c "composer install"

#  symfony-encore-builder:
#    image: node:latest
#    working_dir: /app
#    volumes:
#      - .:/app
#    command: bash -c "yarn install && yarn encore production"
    
#  member-module-builder:
#    image: node:latest
#    working_dir: /app
#    volumes:
#      - .:/app
#    command: bash -c "cd frontends/member_module/ && npm install && npm run build"
    
#  docs-builder:
#    image: node:latest
#    working_dir: /app
#    volumes:
#      - ./docs:/app
#    command: bash -c "npm install && npm run docs:build"
