# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

# -- top navigation ------------------------------------------------------------------------------------------

top:
    -   label: Judo School
        class: fa fa-medal
        submenu:
            -   label: Onze Missie
                link: pagina/125
            -   label: Onze Visie
                link: pagina/126
            -   label: Locaties
                submenu:
                    -   label: Hofstade
                        link: locatie/122
                    -   label: Haacht
                        link: locatie/123
                    -   label: Heist op den Berg
                        link: locatie/124
    -   label: Praktische info
        class: fa fa-circle-info
        submenu:
            -   label: Lessenschema
                link: pagina/130
            -   label: Opleidingsplan jeugd
                link: pagina/131
            -   label: Tarieven
                link: pagina/132
            -   label: Reglement
                link: pagina/133
            -   label: Online inschrijven
                link: inschrijven
            -   label: GDPR - Privacy Verklaring
                link: pagina/134

    -   label: Over ons
        class: fa fa-users
        link: trainers
    -   label: Nieuws
        class: fa fa-bullhorn
        link: nieuws
    -   label: Links
        class: fa fa-link
        link: pagina/128
    -   label: Contact
        class: fa fa-envelope
        link: pagina/127

# -- footer colums ------------------------------------------------------------------------------------------

footer_c1:
    -   label: Onze Missie
        link: pagina/125
    -   label: Onze Visie
        link: pagina/126
    -   label: Locaties
        submenu:
            -   label: Hofstade
                link: locatie/122
            -   label: Haacht
                link: locatie/123
            -   label: Heist op den Berg
                link: locatie/124

footer_c2:
    -   label: Over ons
        link: trainers
    -   label: Praktische informatie
        submenu:
            -   label: Lessenschema
                link: pagina/130
            -   label: Opleidingsplan jeugd
                link: pagina/131
            -   label: Tarieven
                link: pagina/132
            -   label: Reglement
                link: pagina/133
            -   label: GDPR - Privacy Verklaring
                link: pagina/134

footer_c3:
    -   label: Online inschrijven
        link: inschrijven
    -   label: Nieuws
        link: nieuws
    -   label: Links
        link: pagina/128
    -   label: Sponsors
        link: pagina/129
    -   label: Contact
        link: pagina/127

