# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Voeg een tag toe. Maak een nieuwe tag door een spatie of een komma te typen."
    allow_spaces: false
    #listing_template: tag-listing.twig #custom template
    required: false

groups:
    slug: groups
    singular_slug: group
    behaves_like: grouping
    options: { main: "The main group", meta: "Meta group", other: "The other stuff" }
    has_sortorder: true
    required: false

categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [ nieuws, event, hofstade, haacht, heist op den berg ]
    required: false
